// <auto-generated />
using System;
using AplicacionWebMobileMetriks.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AplicacionWebMobileMetriks.Migrations.Catalogos
{
    [DbContext(typeof(CatalogosContext))]
    partial class CatalogosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AplicacionWebMobileMetriks.Models.ClaveProdServ", b =>
                {
                    b.Property<string>("CClaveProdServ")
                        .HasColumnName("c_ClaveProdServ")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<bool?>("EnUso")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("('FALSE')");

                    b.HasKey("CClaveProdServ");

                    b.ToTable("ClaveProdServ");
                });

            modelBuilder.Entity("AplicacionWebMobileMetriks.Models.ClaveUnidad", b =>
                {
                    b.Property<string>("CClaveUnidad")
                        .HasColumnName("c_ClaveUnidad")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<bool?>("EnUso")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("('FALSE')");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("CClaveUnidad");

                    b.ToTable("ClaveUnidad");
                });

            modelBuilder.Entity("AplicacionWebMobileMetriks.Models.CodigoPostal", b =>
                {
                    b.Property<long>("IdCodigoPostal")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idCodigoPostal")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CCodigoPostal")
                        .IsRequired()
                        .HasColumnName("c_CodigoPostal")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("CEstado")
                        .IsRequired()
                        .HasColumnName("c_Estado")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("CLocalidad")
                        .HasColumnName("c_Localidad")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("CMunicipio")
                        .HasColumnName("c_Municipio")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<bool?>("EnUso")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("('FALSE')");

                    b.HasKey("IdCodigoPostal");

                    b.ToTable("CodigoPostal");
                });

            modelBuilder.Entity("AplicacionWebMobileMetriks.Models.FormaPago", b =>
                {
                    b.Property<long>("IdFormaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idFormaPago")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CFormaPago")
                        .IsRequired()
                        .HasColumnName("c_FormaPago")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<bool?>("EnUso")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("('FALSE')");

                    b.HasKey("IdFormaPago");

                    b.ToTable("FormaPago");
                });

            modelBuilder.Entity("AplicacionWebMobileMetriks.Models.Impuesto", b =>
                {
                    b.Property<long>("IdImpuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idImpuesto")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CImpuesto")
                        .IsRequired()
                        .HasColumnName("c_Impuesto")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<bool?>("EnUso")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("('FALSE')");

                    b.Property<string>("Tipo")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("IdImpuesto");

                    b.ToTable("Impuesto");
                });

            modelBuilder.Entity("AplicacionWebMobileMetriks.Models.MetodoPago", b =>
                {
                    b.Property<long>("IdMetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idMetodoPago")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CMetodoPago")
                        .IsRequired()
                        .HasColumnName("c_MetodoPago")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<bool?>("EnUso")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("('FALSE')");

                    b.HasKey("IdMetodoPago");

                    b.ToTable("MetodoPago");
                });

            modelBuilder.Entity("AplicacionWebMobileMetriks.Models.Moneda", b =>
                {
                    b.Property<long>("IdMoneda")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idMoneda")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CMoneda")
                        .IsRequired()
                        .HasColumnName("c_Moneda")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("Decimales");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<bool?>("EnUso")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("('FALSE')");

                    b.Property<string>("PorcentajeVariacion")
                        .HasMaxLength(20);

                    b.HasKey("IdMoneda")
                        .HasName("PK_Moneda_1");

                    b.ToTable("Moneda");
                });

            modelBuilder.Entity("AplicacionWebMobileMetriks.Models.Pais", b =>
                {
                    b.Property<long>("IdPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idPais")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPais")
                        .IsRequired()
                        .HasColumnName("c_Pais")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<bool?>("EnUso")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("('FALSE')");

                    b.HasKey("IdPais");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("AplicacionWebMobileMetriks.Models.RegimenFiscal", b =>
                {
                    b.Property<long>("IdRegimenFiscal")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idRegimenFiscal")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CRegimenFiscal")
                        .IsRequired()
                        .HasColumnName("c_RegimenFiscal")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<bool?>("EnUso")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("('FALSE')");

                    b.Property<bool>("PerFisica");

                    b.Property<bool>("PerMoral");

                    b.HasKey("IdRegimenFiscal");

                    b.ToTable("RegimenFiscal");
                });

            modelBuilder.Entity("AplicacionWebMobileMetriks.Models.TipoDeComprobante", b =>
                {
                    b.Property<long>("IdTipoDeComprobante")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idTipoDeComprobante")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CTipoDeComprobante")
                        .IsRequired()
                        .HasColumnName("c_TipoDeComprobante")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<bool?>("EnUso")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("('FALSE')");

                    b.HasKey("IdTipoDeComprobante");

                    b.ToTable("TipoDeComprobante");
                });

            modelBuilder.Entity("AplicacionWebMobileMetriks.Models.TipoFactor", b =>
                {
                    b.Property<long>("IdTipoFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idTipoFactor")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CTipoFactor")
                        .IsRequired()
                        .HasColumnName("c_TipoFactor")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<bool?>("EnUso")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("('FALSE')");

                    b.HasKey("IdTipoFactor");

                    b.ToTable("TipoFactor");
                });

            modelBuilder.Entity("AplicacionWebMobileMetriks.Models.TipoRelacion", b =>
                {
                    b.Property<long>("IdTipoRelacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idTipoRelacion")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CTipoRelacion")
                        .IsRequired()
                        .HasColumnName("c_TipoRelacion")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false);

                    b.Property<bool?>("EnUso")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("('FALSE')");

                    b.HasKey("IdTipoRelacion");

                    b.ToTable("TipoRelacion");
                });

            modelBuilder.Entity("AplicacionWebMobileMetriks.Models.UsoCfdi", b =>
                {
                    b.Property<long>("IdUsoCfdi")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idUsoCFDI")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CUsoCfdi")
                        .IsRequired()
                        .HasColumnName("c_UsoCFDI")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false);

                    b.Property<bool?>("EnUso")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("('FALSE')");

                    b.Property<bool>("PerFisica");

                    b.Property<bool>("PerMoral");

                    b.HasKey("IdUsoCfdi");

                    b.ToTable("UsoCFDI");
                });
#pragma warning restore 612, 618
        }
    }
}
