// <auto-generated />
using System;
using AplicacionWebMobileMetriks.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AplicacionWebMobileMetriks.Migrations.BaseDBMigrations
{
    [DbContext(typeof(BaseDB))]
    [Migration("20190715140218_ModeloConceptos")]
    partial class ModeloConceptos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AplicacionWebMobileMetriks.Models.Conceptos", b =>
                {
                    b.Property<int>("IdConceptos")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaveProdServ")
                        .IsRequired();

                    b.Property<string>("ClaveUnidad")
                        .IsRequired();

                    b.Property<string>("CuentaPredial");

                    b.Property<string>("Descripcion")
                        .IsRequired();

                    b.Property<string>("Identificador")
                        .IsRequired();

                    b.Property<string>("Unidad");

                    b.Property<double>("ValorUnitario");

                    b.HasKey("IdConceptos");

                    b.ToTable("Conceptos");
                });

            modelBuilder.Entity("AplicacionWebMobileMetriks.Models.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Correo");

                    b.Property<string>("Extension");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<int>("ReceptorId");

                    b.Property<string>("Telefono");

                    b.Property<string>("Ubicacion");

                    b.HasKey("Id");

                    b.HasIndex("ReceptorId");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("AplicacionWebMobileMetriks.Models.Emisor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Calle");

                    b.Property<int>("CodigoPostal");

                    b.Property<string>("Colonia");

                    b.Property<string>("Correo")
                        .IsRequired();

                    b.Property<string>("Curp");

                    b.Property<string>("Estado");

                    b.Property<string>("Imagen");

                    b.Property<string>("Localidad");

                    b.Property<string>("Municipio");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<int>("NumExterior");

                    b.Property<int>("NumInterior");

                    b.Property<string>("Pais")
                        .IsRequired();

                    b.Property<string>("RFC")
                        .IsRequired();

                    b.Property<string>("Referencia");

                    b.Property<string>("Telefono")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("emisor");
                });

            modelBuilder.Entity("AplicacionWebMobileMetriks.Models.Receptores", b =>
                {
                    b.Property<int>("IdReceptor")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("C_Moneda")
                        .IsRequired();

                    b.Property<string>("Calle")
                        .IsRequired();

                    b.Property<string>("Cliente")
                        .IsRequired();

                    b.Property<int>("CodigoPostal");

                    b.Property<long>("IdFormaPago");

                    b.Property<long>("IdPais");

                    b.Property<long>("IdUsoCfdi");

                    b.Property<string>("Identificador")
                        .IsRequired();

                    b.Property<string>("NumIdRegTrib");

                    b.Property<string>("RFC")
                        .IsRequired();

                    b.HasKey("IdReceptor");

                    b.ToTable("Receptores");
                });

            modelBuilder.Entity("AplicacionWebMobileMetriks.Models.RegimenEmisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RegimenFiscalId");

                    b.HasKey("Id");

                    b.ToTable("RegimenEmisores");
                });

            modelBuilder.Entity("AplicacionWebMobileMetriks.Models.Contacto", b =>
                {
                    b.HasOne("AplicacionWebMobileMetriks.Models.Receptores", "Receptores")
                        .WithMany()
                        .HasForeignKey("ReceptorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
